[package]

name = "heroku-env"
version = "0.0.4"
authors = [ "Jeremie Veillet <jeremie.veillet@gmail.com>" ]

[dependencies]
clap = "2.31"
reqwest = "0.8.5"
dotenv = "0.11.0"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
