version: "3"
services:
  app:
    build:
      context: .
    user: rusty
    volumes:
      - ".:/home/rusty/heroku-env-rs"
      - "./config/config.yml:/home/rusty/.heroku-env/config.yml"
    command: cargo run -- push
