version: "3"
services:
  app:
    build:
      context: .
    user: rusty
    volumes:
      - ".:/home/rusty/src/heroku-env"
      - "./config/config.yml:/home/rusty/.heroku-env/config.yml"
    command: cargo run
