max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
merge_derives = true
use_try_shorthand = false
force_explicit_abi = true
use_field_init_shorthand = false

